language: ruby

cache:
  - bundler

before_install:
  - gem install bundler
  - bundle install --jobs=3 --retry=3

before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate

env:
  - DB: sqlite

script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake
